# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Constraints/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/aes_128_encryption_overlay/aes_128_encryption_overlay.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_128_encryption_overlay || ORIG_REF_NAME==aes_128_encryption_overlay} -quiet] -quiet

# IP: bd/aes_128_encryption_overlay/ip/aes_128_encryption_overlay_aes_128_encryption_ip_0_0/aes_128_encryption_overlay_aes_128_encryption_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_128_encryption_overlay_aes_128_encryption_ip_0_0 || ORIG_REF_NAME==aes_128_encryption_overlay_aes_128_encryption_ip_0_0} -quiet] -quiet

# IP: bd/aes_128_encryption_overlay/ip/aes_128_encryption_overlay_processing_system7_0_1/aes_128_encryption_overlay_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_128_encryption_overlay_processing_system7_0_1 || ORIG_REF_NAME==aes_128_encryption_overlay_processing_system7_0_1} -quiet] -quiet

# IP: bd/aes_128_encryption_overlay/ip/aes_128_encryption_overlay_ps7_0_axi_periph_1/aes_128_encryption_overlay_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_128_encryption_overlay_ps7_0_axi_periph_1 || ORIG_REF_NAME==aes_128_encryption_overlay_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/aes_128_encryption_overlay/ip/aes_128_encryption_overlay_rst_ps7_0_100M_0/aes_128_encryption_overlay_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_128_encryption_overlay_rst_ps7_0_100M_0 || ORIG_REF_NAME==aes_128_encryption_overlay_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/aes_128_encryption_overlay/ip/aes_128_encryption_overlay_auto_pc_0/aes_128_encryption_overlay_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_128_encryption_overlay_auto_pc_0 || ORIG_REF_NAME==aes_128_encryption_overlay_auto_pc_0} -quiet] -quiet

# XDC: bd/aes_128_encryption_overlay/aes_128_encryption_overlay_ooc.xdc
