# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pynq-z2 constraints/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/aes_128_overlay/aes_128_overlay.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_128_overlay || ORIG_REF_NAME==aes_128_overlay} -quiet] -quiet

# IP: bd/aes_128_overlay/ip/aes_128_overlay_processing_system7_0_0/aes_128_overlay_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_128_overlay_processing_system7_0_0 || ORIG_REF_NAME==aes_128_overlay_processing_system7_0_0} -quiet] -quiet

# IP: bd/aes_128_overlay/ip/aes_128_overlay_aes_128_ip_0_0/aes_128_overlay_aes_128_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_128_overlay_aes_128_ip_0_0 || ORIG_REF_NAME==aes_128_overlay_aes_128_ip_0_0} -quiet] -quiet

# IP: bd/aes_128_overlay/ip/aes_128_overlay_ps7_0_axi_periph_0/aes_128_overlay_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_128_overlay_ps7_0_axi_periph_0 || ORIG_REF_NAME==aes_128_overlay_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/aes_128_overlay/ip/aes_128_overlay_rst_ps7_0_100M_0/aes_128_overlay_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_128_overlay_rst_ps7_0_100M_0 || ORIG_REF_NAME==aes_128_overlay_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/aes_128_overlay/ip/aes_128_overlay_auto_pc_0/aes_128_overlay_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes_128_overlay_auto_pc_0 || ORIG_REF_NAME==aes_128_overlay_auto_pc_0} -quiet] -quiet

# XDC: bd/aes_128_overlay/aes_128_overlay_ooc.xdc
