webtalk_init -webtalk_dir D:/Senior Design/Technical Work/Vivado/AES_128_Decryption_IP/ip_repo/aes_128_decryption_ip_v1_0_project/aes_128_decryption_ip_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/test_aes_128_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jul 28 05:11:38 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "71b7cacd-f3bf-43d8-8881-83b2a7f1c66b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "07396e82ada643e6a91984724ba1a5b7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "872 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "12084_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3032398196 -regid "" -xml D:/Senior Design/Technical Work/Vivado/AES_128_Decryption_IP/ip_repo/aes_128_decryption_ip_v1_0_project/aes_128_decryption_ip_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/test_aes_128_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Senior Design/Technical Work/Vivado/AES_128_Decryption_IP/ip_repo/aes_128_decryption_ip_v1_0_project/aes_128_decryption_ip_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/test_aes_128_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Senior Design/Technical Work/Vivado/AES_128_Decryption_IP/ip_repo/aes_128_decryption_ip_v1_0_project/aes_128_decryption_ip_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/test_aes_128_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
