# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Senior Design/Technical Work/Vivado/AES_128_Encryption_Overlay/AES_128_Encryption_Overlay.srcs/sources_1/bd/aes_128_encryption_overlay/ip/aes_128_encryption_overlay_processing_system7_0_1/aes_128_encryption_overlay_processing_system7_0_1.xci
# IP: The module: 'aes_128_encryption_overlay_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Senior Design/Technical Work/Vivado/AES_128_Encryption_Overlay/AES_128_Encryption_Overlay.srcs/sources_1/bd/aes_128_encryption_overlay/ip/aes_128_encryption_overlay_processing_system7_0_1/aes_128_encryption_overlay_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes_128_encryption_overlay_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Senior Design/Technical Work/Vivado/AES_128_Encryption_Overlay/AES_128_Encryption_Overlay.srcs/sources_1/bd/aes_128_encryption_overlay/ip/aes_128_encryption_overlay_processing_system7_0_1/aes_128_encryption_overlay_processing_system7_0_1.xci
# IP: The module: 'aes_128_encryption_overlay_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Senior Design/Technical Work/Vivado/AES_128_Encryption_Overlay/AES_128_Encryption_Overlay.srcs/sources_1/bd/aes_128_encryption_overlay/ip/aes_128_encryption_overlay_processing_system7_0_1/aes_128_encryption_overlay_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes_128_encryption_overlay_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
